name: msm-dp

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  msm-dp:
    name: msm-dp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      #      - name: golangci-lint
      #        uses: golangci/golangci-lint-action@v3
      #        with:
      #          version: v1.29
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: harbor.eticloud.io
        with:
          username: ${{ secrets.HARBOR_PASSWORD }}
          password: ${{ secrets.HARBOR_USERNAME }}
      - name: Build Container and Push to Docker Hub
        run: docker buildx build --push --platform linux/amd64,linux/arm64 -t ciscolabs/msm-proxy:latest .
